In [1]:
import numpy as np
import pandas as pd

In [2]:
rng = np.random.RandomState(42)
x = rng.rand(1000000)
y = rng.rand(1000000)
%timeit x + y

6.47 ms ± 152 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [3]:
x + y

array([0.96969574, 1.31543145, 0.73736956, ..., 1.1011828 , 0.76733033,
       1.62106496])

In [4]:
pd.DataFrame(x + y)

               0
0       0.969696
1       1.315431
2       0.737370
3       1.159746
4       1.052589
5       0.687711
6       0.838571
7       1.028130
8       0.738413
9       1.602016
10      0.803583
11      1.317320
12      1.632615
13      0.287665
14      0.699725
15      1.064861
16      1.147843
17      0.896010
18      0.660794
19      1.159094
20      0.878754
21      0.961518
22      0.558662
23      1.350895
24      0.816190
25      1.040538
26      0.798902
27      0.873944
28      1.402842
29      0.779200
...          ...
999970  0.963362
999971  1.436101
999972  0.816230
999973  1.016163
999974  0.429398
999975  1.401912
999976  1.609234
999977  1.578745
999978  0.288839
999979  0.955810
999980  0.453938
999981  0.789812
999982  1.873169
999983  0.500147
999984  0.535036
999985  0.991152
999986  0.841590
999987  1.492455
999988  0.653668
999989  1.149412
999990  0.581368
999991  1.639791
999992  0.786213
999993  1.088012
999994  1.024760
999995  1.348660
999996  1.342479
999997  1.101183
999998  0.767330
999999  1.621065

[1000000 rows x 1 columns]

In [5]:
%timeit np.fromiter((xi + yi for xi, yi in zip(x, y)), dtype=x.dtype, count=len(x))

474 ms ± 14.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [7]:
mask = (x > 0.5) & (y < 0.5)
mask

array([False,  True,  True, ..., False, False, False])

In [10]:
(x > 0.5) / (y < 0.5)

c:\users\mercy mueni mwangi\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
c:\users\mercy mueni mwangi\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.

array([nan,  1.,  1., ..., nan,  0., inf])